### PR TITLE
Spectrum MPI, does not have MPIX_Query_cuda_support

### LINKED ISSUE #357: `MPI.has_cuda()` fails on Spectrum MPI
using the test script

```
using MPI
MPI.Init()

@show MPI.has_cuda()
```

fails with

```
ERROR: ERROR: ERROR: ERROR: LoadError: LoadError: LoadError: LoadError: ccall: could not find function MPIX_Query_cuda_support in library /opt/ibm/spectrum_mpi/lib/libmpi_ibm.soccall: could not find function MPIX_Query_cuda_support in library
/opt/ibm/spectrum_mpi/lib/libmpi_ibm.soccall: could not find function MPIX_Query_cuda_support in library /opt/ibm/spectrum_mpi/lib/libmpi_ibm.so
Stacktrace:
Stacktrace:
Stacktrace:ccall: could not find function MPIX_Query_cuda_support in library /opt/ibm/spectrum_mpi/lib/libmpi_ibm.so
Stacktrace:
 [1]
```

### PR DESCRIPTION
**Pull request by vchuravy**
fixes #357

### CODE REVIEW

File: src/environment.jl [hunk 1]
```diff
@@ -172,8 +172,12 @@ or `false`.
 function has_cuda()
     flag = get(ENV, "JULIA_MPI_HAS_CUDA", nothing)
     if flag === nothing
-        # Only Open MPI provides a function to check CUDA support
-        @static if startswith(MPI_LIBRARY_VERSION, "Open MPI")
+        # Only OpenMPI provides a function to check CUDA support
+        # - Spectrum MPI is an OpenMPI, but IBM removed the functionality
+        #   check, therefore force true
+        @static if occursin(r".*Spectrum.*", MPI_LIBRARY_VERSION)
```
Comment (simonbyrne) [inline src/environment.jl]: Is this sufficiently specific to avoid picking up anything else? Should we make it match `"IBM Spectrum MPI"`?

Comment (simonbyrne) [reply src/environment.jl]: also, can't you just write
```julia
occursin("Spectrum", MPI_LIBRARY_VERSION)
```
